### ISSUE TITLE
SteamTractorObject in log file

### ISSUE THREAD

**Issue by chrisbitz** [EcoModsDevelopers/Asphalt-ModKit#35]
Since installing, I'm getting a lot of entries in the log file like this:
[09:01:19] Exception when updating object SteamTractorObject: Sequence contains no elements

they're appearing whenever someone drives a tractor.

I also installed the JDGarbage mod that uses your modkit, but I can't imagine what that could have to do with tractors :-)

**Comment by lordmampf** [comment]
No other user reported this issue. Looks like it's not related to Asphalt.
