### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by lucasninja26** [EcoModsDevelopers/Asphalt-ModKit#45]
I've moved almost everything in every way from the download folder to the mods folder under server, and everytime I start eco, I just get a timed out error

**Comment by Lars225** [comment]
Can you send your Log and Dump File?

**Comment by lucasninja26** [comment]
Okay, first, how do I correctly install it? It says "Copy the file from the 'Mods' folder to your server 'Mods' Folder, and I dont know what folders and certain locations it means, I don't want to send inccorect information

**Comment by Lars225** [comment]
You go to your EcoServer Diretory. In the same directory where the mods Folder is located is the EcoServer.exe. And in this mods Folder you must Copy the dll files

**Comment by lucasninja26** [comment]
The dll files from what?

**Comment by Lars225** [comment]
From the Asphalt Modkit

**Comment by lucasninja26** [comment]
I only see CS Files

**Comment by Lars225** [comment]
now i understand your problem... pls download from here: https://forum.play.eco/resources/asphalt-modkit-modding-framework.47/

**Comment by lucasninja26** [comment]
Where is the download button, I'm new to this eco mod stuff

**Comment by Lars225** [comment]
you must register and login

**Comment by lucasninja26** [comment]
Ah, let me try

**Comment by lucasninja26** [comment]
It works now! Thank you so much!
